### PR TITLE
Android app testing

### PR DESCRIPTION
**Pull request by ferenckata**
## Description
Integrating Codecov to Travis CI

## Related issue(s)
Issue #52

### CODE REVIEW

**Comment by ferenckata** [comment]
It seems all right, because it is the first time codecov is run

**Comment by platisd** [comment]
What ultimately matters is [this](https://codecov.io/gh/DIT112-V19/group-10/pull/53/tree?path=carMobileApp%2Fapp%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgroup10app) :+1:

**Comment by ferenckata** [comment]
@platisd It seems that only the instrumented tests were considered in this percentage, how do I make sure that it also includes the tests run in pc? I think travis does check them, only that it is not reported to codecov. Am I wrong?

**Comment by platisd** [comment]
Can you please send me a link to the tests you're referring to and I'll have a look later

**Comment by ferenckata** [comment]
They are not many:
https://github.com/DIT112-V19/group-10/tree/master/carMobileApp/app/src/test/java/com/group10app

**Comment by platisd** [comment]
I believe you also need to generate the test coverage reports. They are a separate `gradlew` target. Have a look [here](https://github.com/platisd/indoor-navigation-system/blob/b34dc9ff0ede7fa0fc1725830bfad4d9d14b9886/run_coverage.sh#L27-L32).

**Comment by ferenckata** [comment]
Done, thank you :) :)

**Review by totsteps — APPROVED** [review]
Great job with `testing` and `code-coverage`. Thanks

**Comment by platisd** [comment]
Good job! :+1: 
You should also display the CI and test coverage status proudly on your `README.md` :grin:

**Pull request merged**
