### PR TITLE
Initial android studio project for mobile app

### PR DESCRIPTION
**Pull request by florencefranz**
This is the initial, empty android studio project so we can start to build the mobile app. Related to: #23

### CODE REVIEW

**Review by platisd — DISMISSED** [review]
What issues/stories is this pull request related to or is solving? Please specify in pull request description.

**Comment by florencefranz** [comment]
@platisd I've updated the request.

**Review by totsteps — COMMENTED** [review]
LGTM. For now, we can have this as a separate branch.

**Comment by platisd** [comment]
> LGTM. For now, we can have this as a separate branch.

Why delay integration? Only `master` branch will be taken into consideration.

**Review by totsteps — DISMISSED** [review]

**Pull request closed without merging**
