### PR TITLE
add code quality feature

### PR DESCRIPTION
**Pull request by ferenckata**
## Description
Emphasize code quality feature in README file as we consider it important for our stakeholders.

## Related issue(s)
Issues #44 , #53 , #52

### CODE REVIEW

**Comment by florencefranz** [comment]
@ferenckata Is there an issue with the failing test?

**Comment by platisd** [comment]
Ah, the fun begins! Is it the tests that are written in a non-optimum way and they fail? Is it the CI configuration that is not the correct one (e.g. missing something)? Or is it an actual problem in the code?

I'll leave the joy of finding that out to you!  :grin: 
I had a quick look and I saw that one instrumented test was failing so there's either something wrong in the code or the test needs to be updated. Try running the instrumented tests locally on your computers and see what exactly happens. :+1:

**Comment by ferenckata** [comment]
Yeah, since the other branch was merged, the tests need to be updated I believe. In progress :) The fun of testing after writing the code

**Review by Amirneutron — COMMENTED** [review]
Test reviewed and passed successfully!!!

**Review by Amirneutron — APPROVED** [review]

**Comment by platisd** [comment]
You should also add the TravisCI and Codecov badged to your readme! :+1:

**Pull request merged**
